<<<<<<< HEAD
# Generated by Django 4.2 on 2024-06-06 23:18
=======
# Generated by Django 4.2 on 2024-06-11 17:35
>>>>>>> d2087161ed664a5d99d597d283d3efa8089d7dc6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
>>>>>>> d2087161ed664a5d99d597d283d3efa8089d7dc6
            name='Lecheria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
<<<<<<< HEAD
=======
            options={
                'verbose_name_plural': 'Lecherias',
            },
>>>>>>> d2087161ed664a5d99d597d283d3efa8089d7dc6
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
<<<<<<< HEAD
=======
            options={
                'verbose_name_plural': 'Poblaciones',
            },
>>>>>>> d2087161ed664a5d99d597d283d3efa8089d7dc6
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
            ],
<<<<<<< HEAD
=======
            options={
                'verbose_name_plural': 'Rutas',
            },
>>>>>>> d2087161ed664a5d99d597d283d3efa8089d7dc6
        ),
        migrations.CreateModel(
            name='Rotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('fecha_evaluacion', models.DateField()),
                ('rotos_reportados', models.IntegerField()),
                ('lecheria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.lecheria')),
            ],
<<<<<<< HEAD
=======
            options={
                'verbose_name_plural': 'Rotos',
            },
>>>>>>> d2087161ed664a5d99d597d283d3efa8089d7dc6
        ),
        migrations.AddField(
            model_name='lecheria',
            name='poblacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.poblacion'),
        ),
        migrations.AddField(
            model_name='lecheria',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.ruta'),
        ),
    ]
