<<<<<<< HEAD
# Generated by Django 4.2 on 2024-06-07 23:17
=======
# Generated by Django 4.2 on 2024-06-12 18:06
>>>>>>> d2087161ed664a5d99d597d283d3efa8089d7dc6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecheria',
            options={'verbose_name_plural': 'Lecherias'},
        ),
        migrations.AlterModelOptions(
            name='poblacion',
            options={'verbose_name_plural': 'Poblaciones'},
        ),
        migrations.AlterModelOptions(
            name='rotos',
            options={'verbose_name_plural': 'Rotos'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'verbose_name_plural': 'Rutas'},
        ),
    ]
