# Generated by Django 4.2 on 2024-08-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.AlterField(
            model_name='cabezal',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.maquina'),
        ),
        migrations.AlterField(
            model_name='cabezal',
            name='nombre',
            field=models.CharField(help_text='Ingrese una letra de la A a la F. A y B para la máquina 1, C y D para la máquina 2, E y F para la máquina 3.', max_length=1),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=100),
        ),
    ]
