# Generated by Django 4.2 on 2024-07-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], max_length=100),
        ),
    ]
