# Generated by Django 4.2 on 2024-07-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
