# Generated by Django 4.2 on 2024-07-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_area_alter_usuario_area'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], max_length=100),
        ),
    ]
