# Generated by Django 4.2 on 2024-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquina',
            options={'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterField(
            model_name='maquina',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='maquina',
            unique_together={('numero', 'planta')},
        ),
    ]
