# Generated by Django 4.2 on 2024-08-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_maquina_options_alter_maquina_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecheria',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
