# Generated by Django 4.2 on 2024-08-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_remove_proveedor_contacto_alter_cabezal_maquina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silo',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='silo',
            unique_together={('numero', 'planta')},
        ),
    ]
