# Generated by Django 4.2 on 2024-06-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_planta_producto_turno_silo_proveedor_maquina_cabezal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabezal',
            options={'verbose_name_plural': 'Cabezales'},
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'verbose_name_plural': 'Maquinas'},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={'verbose_name_plural': 'Plantas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='silo',
            options={'verbose_name_plural': 'Silos'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name_plural': 'Turnos'},
        ),
    ]
