# Generated by Django 4.2 on 2024-06-24 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_cabezal_options_alter_maquina_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de productos',
            },
        ),
        migrations.RenameField(
            model_name='cabezal',
            old_name='codigo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='nombre',
        ),
        migrations.AddField(
            model_name='maquina',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cabezal',
            name='maquina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogos.maquina'),
        ),
        migrations.AlterField(
            model_name='silo',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipoproducto'),
            preserve_default=False,
        ),
    ]
