# Generated by Django 4.2 on 2024-08-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_alter_turno_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='activo',
            new_name='estatus',
        ),
        migrations.AlterField(
            model_name='turno',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
