# Generated by Django 4.2 on 2024-09-09 23:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabOrdenDesp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(blank=True, max_length=512, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDespPNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsRuta', models.CharField(blank=True, max_length=100, verbose_name='Responsables rutas')),
                ('numEcoUnidad', models.IntegerField(default=0)),
                ('tempInicial', models.FloatField(default=0.0)),
                ('dotacion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('canastillas', models.IntegerField(default=0)),
                ('encabezado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distribucion.encabordendesp')),
                ('ruta', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='catalogos.ruta')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de Despacho',
            },
        ),
    ]
