# Generated by Django 4.2 on 2024-09-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_alter_turno_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalSelladosEncab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField()),
                ('fechaEvaluacion', models.DateField()),
                ('programaSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.producto', verbose_name='Tipo de muestra')),
            ],
        ),
        migrations.CreateModel(
            name='MalSellados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia o Localidad')),
                ('noRotos', models.IntegerField()),
                ('sellado', models.IntegerField(choices=[(1, 'Horizontal'), (2, 'Vertical')], verbose_name='Sellado')),
                ('imputFabricacion', models.IntegerField(choices=[(1, 'Perforado sist. de envasado'), (2, 'Picado por canastilla'), (3, 'Polietileno picado'), (4, 'Bolsa chica')], verbose_name='Imputables a la fabricación')),
                ('imputTransportacion', models.IntegerField(choices=[(1, 'Pellizco por canastilla'), (2, 'Por Gancho'), (3, 'Caida estiba')], verbose_name='Imputables a la transportación')),
                ('causInt', models.IntegerField(choices=[(1, 'Envase mordido'), (2, 'Cortado')], verbose_name='Causas intencionales')),
                ('MalSelladosencab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto_no_conforme.malselladosencab')),
                ('lecheria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.lecheria', verbose_name='Lecheria')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.ruta', verbose_name='Ruta')),
            ],
        ),
    ]
