# Generated by Django 4.2 on 2024-09-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_no_conforme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malsellados',
            old_name='MalSelladosencab',
            new_name='encabezado',
        ),
    ]
