# Generated by Django 4.2 on 2024-10-14 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto_no_conforme', '0002_rename_malselladosencab_malsellados_encabezado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malselladosencab',
            name='fechaEvaluacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='malselladosencab',
            name='fechaVenta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de venta'),
        ),
    ]
