# Generated by Django 4.2 on 2024-07-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.FloatField()),
                ('temperatiura', models.FloatField()),
                ('densidadgml', models.FloatField()),
                ('grasasgl', models.FloatField()),
                ('snggl', models.FloatField()),
                ('proteinagl', models.FloatField()),
                ('ph', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTemporal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.FloatField()),
                ('temperatiura', models.FloatField()),
                ('densidadgml', models.FloatField()),
                ('grasasgl', models.FloatField()),
                ('snggl', models.FloatField()),
                ('proteinagl', models.FloatField()),
                ('ph', models.FloatField()),
            ],
        ),
    ]
