# Generated by Django 4.2 on 2024-06-15 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicionFisioquimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.FloatField()),
                ('temperatiura', models.FloatField()),
                ('densidadgml', models.FloatField()),
                ('grasasgl', models.FloatField()),
                ('snggl', models.FloatField()),
                ('proteinagl', models.FloatField()),
                ('ph', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosDeProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProduccionReal', models.FloatField()),
                ('ProduccionVentas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntosDeEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ModeloTemporal',
        ),
        migrations.AddField(
            model_name='composicionfisioquimica',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.puntosdeevaluacion'),
        ),
    ]
