# Generated by Django 4.2 on 2024-06-28 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncabTablaR49',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(blank=True, max_length=512, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='TablaR49',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numMaquina', models.CharField(max_length=2)),
                ('numDatos', models.IntegerField()),
                ('promedio', models.IntegerField()),
                ('desvStd', models.IntegerField()),
                ('maximo', models.IntegerField()),
                ('minimo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pesoenvvacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('cabezal', models.CharField(default=0, max_length=2, verbose_name='Cabezal')),
                ('maquina', models.IntegerField()),
                ('planta', models.CharField(default=0, max_length=4)),
                ('proveedor', models.CharField(default=0, max_length=30)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.encabtablar49')),
            ],
        ),
        migrations.CreateModel(
            name='Pesobruto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('cabezal', models.CharField(default=0, max_length=2)),
                ('maquina', models.IntegerField(default=0)),
                ('planta', models.CharField(default=0, max_length=4)),
                ('analista', models.CharField(default=0, max_length=30)),
                ('valor', models.IntegerField(default=0)),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.encabtablar49')),
            ],
        ),
        migrations.CreateModel(
            name='Densidadpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('cabezal', models.CharField(default=0, max_length=2, verbose_name='Cabezal')),
                ('planta', models.CharField(default=0, max_length=4)),
                ('silo', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=0, verbose_name='No. Silo')),
                ('turno', models.CharField(choices=[('X', 'X matutino'), ('Y', 'Y vespertino')], default=0, max_length=20, verbose_name='Turno')),
                ('linea', models.CharField(blank=True, max_length=20)),
                ('densidad', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('volumen', models.IntegerField(default=0, verbose_name=' Volumen')),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.encabtablar49')),
            ],
        ),
    ]
