# Generated by Django 4.2 on 2024-06-21 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecheReconsSilosEncab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('periodo_Ini', models.DateField(default=django.utils.timezone.now)),
                ('periodo_Fin', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(blank=True, max_length=512, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='LecheReconsSilos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('silo_Numero', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], verbose_name='No. Silo')),
                ('producto', models.CharField(choices=[('LPD', 'LPD'), ('MLGVRG', 'MLGVRG'), ('FRISIA', 'FRISIA')], max_length=10, verbose_name='Tipo de Producto')),
                ('volumen', models.FloatField(default=0.0, verbose_name=' Volumen')),
                ('aspecto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Aspecto')),
                ('sabor', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Sabor')),
                ('olor', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Olor')),
                ('temperatura', models.FloatField(default=0.0, verbose_name='Temperatura')),
                ('ph', models.FloatField(default=0.0, verbose_name='PH')),
                ('acidez', models.FloatField(default=0.0, verbose_name='Acidez')),
                ('densidad', models.FloatField(default=0.0, verbose_name='Densidad')),
                ('s_g_w_v', models.FloatField(default=0.0, verbose_name='s_g_w_v')),
                ('s_n_g_Stsg_wv', models.FloatField(default=0.0, verbose_name='s_n_g_Stsg_wv')),
                ('st_wv', models.FloatField(default=0.0, verbose_name='st_wv')),
                ('proteina', models.FloatField(default=0.0, verbose_name='Proteína')),
                ('encabezado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.lechereconssilosencab')),
            ],
        ),
    ]
