# Generated by Django 4.2 on 2024-07-31 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_turno_nombre'),
        ('laboratorio_control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_terminado',
            name='acidez',
            field=models.FloatField(default=0.0, verbose_name='Ácidez'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='aspecto',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Aspecto'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='densidad',
            field=models.FloatField(default=0.0, verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='encabezado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.terminadoencab', verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='lotCad',
            field=models.CharField(max_length=10, verbose_name='Fecha de caducidad'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='maquina',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='catalogos.maquina', verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='olor',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Olor'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='planta',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='catalogos.planta', verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.producto', verbose_name='Tipo de muestra'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='proteina',
            field=models.FloatField(default=0.0, verbose_name='Proteína'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='sabor',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Sabor'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='sg',
            field=models.FloatField(default=0.0, verbose_name='S.G'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.silo', verbose_name='Silo'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='sng',
            field=models.FloatField(default=0.0, verbose_name='S.N.G'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='st',
            field=models.FloatField(default=0.0, verbose_name='S.T'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='temperatura',
            field=models.FloatField(default=0.0, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='turno',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='catalogos.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='volumen',
            field=models.FloatField(default=0.0, verbose_name='Volumen'),
        ),
    ]
