# Generated by Django 4.2 on 2024-07-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='densidadpt',
            name='linea',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
