# Generated by Django 4.2 on 2024-06-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_terminado',
            name='olor',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='producto',
            field=models.IntegerField(blank=True, choices=[(1, 'LPD'), (2, 'MLGVRG'), (3, 'FRISIA')], null=True),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='sabor',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='silo',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], null=True),
        ),
    ]
