# Generated by Django 4.2 on 2024-06-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TablaR59',
            new_name='TablaR49',
        ),
    ]
