# Generated by Django 4.2 on 2024-08-09 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio_control_calidad', '0001_initial'),
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pesobruto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lechereconssilos',
            name='encabezado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.lechereconssilosencab'),
        ),
        migrations.AddField(
            model_name='lechereconssilos',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.producto', verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='lechereconssilos',
            name='silo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.silo', verbose_name='No. Silo'),
        ),
        migrations.AddField(
            model_name='densidadpt',
            name='cabezal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cabezal'),
        ),
        migrations.AddField(
            model_name='densidadpt',
            name='encabezado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.encabtablar49'),
        ),
        migrations.AddField(
            model_name='densidadpt',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.planta'),
        ),
        migrations.AddField(
            model_name='densidadpt',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.producto'),
        ),
        migrations.AddField(
            model_name='densidadpt',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.silo'),
        ),
        migrations.AddField(
            model_name='densidadpt',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.turno'),
        ),
    ]
