# Generated by Django 4.2 on 2024-07-31 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lechereconssilos',
            name='encabezado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.lechereconssilosencab', verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='lechereconssilos',
            name='fecha_Hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=' Fecha y Hora'),
        ),
    ]
