# Generated by Django 4.2 on 2024-07-04 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabtablar49',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
