# Generated by Django 4.2 on 2024-06-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_terminado',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
