# Generated by Django 4.2 on 2024-07-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_planta_producto_tipoproducto_turno_silo_proveedor_and_more'),
        ('laboratorio_control_calidad', '0002_alter_producto_terminado_acidez_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_terminado',
            name='acidez',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='aspecto',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='densidad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='lotCad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='maquina',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='catalogos.maquina'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='olor',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='planta',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='catalogos.planta'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='proteina',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='sabor',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='sg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='silo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.silo'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='sng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='st',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='temperatura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='turno',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='catalogos.turno'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='volumen',
            field=models.FloatField(default=0.0),
        ),
    ]
