# Generated by Django 4.2 on 2024-08-14 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='densidadpt',
            name='encabezado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.encabr49v2'),
        ),
        migrations.AlterField(
            model_name='pesobruto',
            name='encabezado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.encabr49v2'),
        ),
        migrations.AlterField(
            model_name='pesoenvvacio',
            name='encabezado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_control_calidad.encabr49v2'),
        ),
    ]
