# Generated by Django 4.2 on 2024-08-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_control_calidad', '0003_alter_densidadpt_encabezado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='densidadpt',
            name='linea',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
