# Generated by Django 4.2 on 2024-07-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_planta_producto_tipoproducto_turno_silo_proveedor_and_more'),
        ('laboratorio_control_calidad', '0006_alter_producto_terminado_aspecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_terminado',
            name='maquina',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.maquina'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='planta',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.planta'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='silo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.silo'),
        ),
        migrations.AlterField(
            model_name='producto_terminado',
            name='turno',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.turno'),
        ),
    ]
